/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package freelauncing.marketplace;

/**
 *
 * @author Abbas Zaheer
 */
public class CreateAGig extends javax.swing.JFrame {

    /**
     * Creates new form CreateAGig
     */
    public CreateAGig() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProfileHeading = new javax.swing.JLabel();
        label_FullName = new javax.swing.JLabel();
        textfield_AddSkill = new javax.swing.JTextField();
        label_FullName1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        label_FullName2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        label_FullName3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        label_FullName4 = new javax.swing.JLabel();
        label_FullName5 = new javax.swing.JLabel();
        textfield_AddSkill1 = new javax.swing.JTextField();
        textfield_AddSkill2 = new javax.swing.JTextField();
        label_FullName6 = new javax.swing.JLabel();
        textfield_AddSkill3 = new javax.swing.JTextField();
        label_FullName7 = new javax.swing.JLabel();
        label_FullName8 = new javax.swing.JLabel();
        textfield_AddSkill4 = new javax.swing.JTextField();
        label_FullName9 = new javax.swing.JLabel();
        textfield_AddSkill5 = new javax.swing.JTextField();
        label_FullName10 = new javax.swing.JLabel();
        textfield_AddSkill6 = new javax.swing.JTextField();
        label_FullName11 = new javax.swing.JLabel();
        combobox_Level = new javax.swing.JComboBox();
        Btn_Back = new javax.swing.JButton();
        Btn_Update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 45, 48));

        ProfileHeading.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        ProfileHeading.setForeground(new java.awt.Color(129, 129, 131));
        ProfileHeading.setText("Create a gig");

        label_FullName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_FullName.setForeground(new java.awt.Color(85, 166, 221));
        label_FullName.setText("Title");

        textfield_AddSkill.setBackground(new java.awt.Color(45, 45, 48));
        textfield_AddSkill.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textfield_AddSkill.setForeground(new java.awt.Color(255, 255, 255));
        textfield_AddSkill.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textfield_AddSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_AddSkillActionPerformed(evt);
            }
        });

        label_FullName1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_FullName1.setForeground(new java.awt.Color(85, 166, 221));
        label_FullName1.setText("About this gig");

        jTextArea1.setBackground(new java.awt.Color(45, 45, 48));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        label_FullName2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_FullName2.setForeground(new java.awt.Color(85, 166, 221));
        label_FullName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_FullName2.setText("Basic pakage");

        jTextArea2.setBackground(new java.awt.Color(45, 45, 48));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setBackground(new java.awt.Color(45, 45, 48));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        label_FullName3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_FullName3.setForeground(new java.awt.Color(85, 166, 221));
        label_FullName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_FullName3.setText("Standard pakage");

        jTextArea4.setBackground(new java.awt.Color(45, 45, 48));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        label_FullName4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_FullName4.setForeground(new java.awt.Color(85, 166, 221));
        label_FullName4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_FullName4.setText("Premium pakage");

        label_FullName5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_FullName5.setForeground(new java.awt.Color(85, 166, 221));
        label_FullName5.setText("Delivery Time");

        textfield_AddSkill1.setBackground(new java.awt.Color(45, 45, 48));
        textfield_AddSkill1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textfield_AddSkill1.setForeground(new java.awt.Color(255, 255, 255));
        textfield_AddSkill1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textfield_AddSkill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_AddSkill1ActionPerformed(evt);
            }
        });

        textfield_AddSkill2.setBackground(new java.awt.Color(45, 45, 48));
        textfield_AddSkill2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textfield_AddSkill2.setForeground(new java.awt.Color(255, 255, 255));
        textfield_AddSkill2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textfield_AddSkill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_AddSkill2ActionPerformed(evt);
            }
        });

        label_FullName6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_FullName6.setForeground(new java.awt.Color(85, 166, 221));
        label_FullName6.setText("Delivery Time");

        textfield_AddSkill3.setBackground(new java.awt.Color(45, 45, 48));
        textfield_AddSkill3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textfield_AddSkill3.setForeground(new java.awt.Color(255, 255, 255));
        textfield_AddSkill3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textfield_AddSkill3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_AddSkill3ActionPerformed(evt);
            }
        });

        label_FullName7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_FullName7.setForeground(new java.awt.Color(85, 166, 221));
        label_FullName7.setText("Delivery Time");

        label_FullName8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_FullName8.setForeground(new java.awt.Color(85, 166, 221));
        label_FullName8.setText("Price in $");

        textfield_AddSkill4.setBackground(new java.awt.Color(45, 45, 48));
        textfield_AddSkill4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textfield_AddSkill4.setForeground(new java.awt.Color(255, 255, 255));
        textfield_AddSkill4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textfield_AddSkill4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_AddSkill4ActionPerformed(evt);
            }
        });

        label_FullName9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_FullName9.setForeground(new java.awt.Color(85, 166, 221));
        label_FullName9.setText("Price in $");

        textfield_AddSkill5.setBackground(new java.awt.Color(45, 45, 48));
        textfield_AddSkill5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textfield_AddSkill5.setForeground(new java.awt.Color(255, 255, 255));
        textfield_AddSkill5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textfield_AddSkill5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_AddSkill5ActionPerformed(evt);
            }
        });

        label_FullName10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_FullName10.setForeground(new java.awt.Color(85, 166, 221));
        label_FullName10.setText("Price in $");

        textfield_AddSkill6.setBackground(new java.awt.Color(45, 45, 48));
        textfield_AddSkill6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textfield_AddSkill6.setForeground(new java.awt.Color(255, 255, 255));
        textfield_AddSkill6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textfield_AddSkill6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_AddSkill6ActionPerformed(evt);
            }
        });

        label_FullName11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_FullName11.setForeground(new java.awt.Color(85, 166, 221));
        label_FullName11.setText("Category");

        combobox_Level.setBackground(new java.awt.Color(129, 129, 131));
        combobox_Level.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combobox_Level.setForeground(new java.awt.Color(255, 255, 255));
        combobox_Level.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose category", "Graphics & Design", "Digital Marketing", "Writing & Translation", "Video & Animation", "Music & Audio", "Programming & Tech", "Business", "Lifestyle" }));

        Btn_Back.setBackground(new java.awt.Color(129, 129, 131));
        Btn_Back.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Btn_Back.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Back.setText("Back");
        Btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BackActionPerformed(evt);
            }
        });

        Btn_Update.setBackground(new java.awt.Color(85, 166, 221));
        Btn_Update.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Btn_Update.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Update.setText("Create");
        Btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_Back)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Update))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(ProfileHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label_FullName1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(label_FullName2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(label_FullName3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addGap(2, 2, 2)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(label_FullName5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(textfield_AddSkill1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(label_FullName6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(textfield_AddSkill2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(label_FullName8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(textfield_AddSkill4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(label_FullName9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(textfield_AddSkill5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(label_FullName11, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(combobox_Level, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(label_FullName4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(label_FullName10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(label_FullName7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(textfield_AddSkill3)
                                                .addComponent(textfield_AddSkill6)))))
                                .addComponent(textfield_AddSkill)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProfileHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_AddSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_FullName1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_FullName11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combobox_Level, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_FullName2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_FullName3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_FullName4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_FullName5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfield_AddSkill1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_FullName6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfield_AddSkill2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_FullName7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfield_AddSkill3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_FullName8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfield_AddSkill4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_FullName9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfield_AddSkill5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_FullName10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfield_AddSkill6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Update)
                    .addComponent(Btn_Back))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfield_AddSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_AddSkillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_AddSkillActionPerformed

    private void textfield_AddSkill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_AddSkill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_AddSkill1ActionPerformed

    private void textfield_AddSkill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_AddSkill2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_AddSkill2ActionPerformed

    private void textfield_AddSkill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_AddSkill3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_AddSkill3ActionPerformed

    private void textfield_AddSkill4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_AddSkill4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_AddSkill4ActionPerformed

    private void textfield_AddSkill5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_AddSkill5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_AddSkill5ActionPerformed

    private void textfield_AddSkill6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_AddSkill6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_AddSkill6ActionPerformed

    private void Btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BackActionPerformed
        this.dispose();
    }//GEN-LAST:event_Btn_BackActionPerformed

    private void Btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UpdateActionPerformed


    }//GEN-LAST:event_Btn_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAGig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAGig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAGig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAGig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAGig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Back;
    private javax.swing.JButton Btn_Update;
    private javax.swing.JLabel ProfileHeading;
    private javax.swing.JComboBox combobox_Level;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel label_FullName;
    private javax.swing.JLabel label_FullName1;
    private javax.swing.JLabel label_FullName10;
    private javax.swing.JLabel label_FullName11;
    private javax.swing.JLabel label_FullName2;
    private javax.swing.JLabel label_FullName3;
    private javax.swing.JLabel label_FullName4;
    private javax.swing.JLabel label_FullName5;
    private javax.swing.JLabel label_FullName6;
    private javax.swing.JLabel label_FullName7;
    private javax.swing.JLabel label_FullName8;
    private javax.swing.JLabel label_FullName9;
    private javax.swing.JTextField textfield_AddSkill;
    private javax.swing.JTextField textfield_AddSkill1;
    private javax.swing.JTextField textfield_AddSkill2;
    private javax.swing.JTextField textfield_AddSkill3;
    private javax.swing.JTextField textfield_AddSkill4;
    private javax.swing.JTextField textfield_AddSkill5;
    private javax.swing.JTextField textfield_AddSkill6;
    // End of variables declaration//GEN-END:variables
}
