/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package freelauncing.marketplace;

/**
 *
 * @author Abbas Zaheer
 */
public class DesigningSec extends javax.swing.JFrame {

    /**
     * Creates new form AccountSetting
     */
    public DesigningSec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btn_SectionGraphic = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        ProfileHeading = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Btn_SectionGraphic1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        Btn_SectionGraphic2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        Btn_SectionGraphic4 = new javax.swing.JButton();
        Btn_SectionGraphic5 = new javax.swing.JButton();
        Btn_SectionGraphic6 = new javax.swing.JButton();
        Btn_SectionGraphic7 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        Btn_SectionGraphic8 = new javax.swing.JButton();
        Btn_SectionGraphic9 = new javax.swing.JButton();
        Btn_SectionGraphic10 = new javax.swing.JButton();
        Btn_SectionGraphic11 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        Btn_SectionGraphic12 = new javax.swing.JButton();
        Btn_SectionGraphic13 = new javax.swing.JButton();
        Btn_SectionGraphic14 = new javax.swing.JButton();
        Btn_SectionGraphic15 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        Btn_SectionGraphic16 = new javax.swing.JButton();
        Btn_SectionGraphic17 = new javax.swing.JButton();
        Btn_SectionGraphic18 = new javax.swing.JButton();
        Btn_SectionGraphic19 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Btn_SectionGraphic.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic.setBorder(null);
        Btn_SectionGraphic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphicActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 122, 204));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(45, 45, 48));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Social Media Design ");

        ProfileHeading.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        ProfileHeading.setForeground(new java.awt.Color(129, 129, 131));
        ProfileHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfileHeading.setText("Graphics & Design");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(45, 45, 48));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Vector Tracing ");

        Btn_SectionGraphic1.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic1.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic1.setBorder(null);
        Btn_SectionGraphic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic1ActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 122, 204));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(45, 45, 48));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Invitations ");

        Btn_SectionGraphic2.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic2.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic2.setBorder(null);
        Btn_SectionGraphic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic2ActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 122, 204));

        Btn_SectionGraphic4.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic4.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic4.setBorder(null);
        Btn_SectionGraphic4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic4ActionPerformed(evt);
            }
        });

        Btn_SectionGraphic5.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic5.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic5.setBorder(null);
        Btn_SectionGraphic5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic5ActionPerformed(evt);
            }
        });

        Btn_SectionGraphic6.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic6.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic6.setBorder(null);
        Btn_SectionGraphic6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic6ActionPerformed(evt);
            }
        });

        Btn_SectionGraphic7.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic7.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic7.setBorder(null);
        Btn_SectionGraphic7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic7ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(45, 45, 48));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Logo Design");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(45, 45, 48));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(" Flyers & Brochures ");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(45, 45, 48));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Packaging Design ");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(45, 45, 48));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Illustration ");

        jSeparator6.setForeground(new java.awt.Color(0, 122, 204));

        jSeparator7.setForeground(new java.awt.Color(0, 122, 204));

        jSeparator8.setForeground(new java.awt.Color(0, 122, 204));

        jSeparator9.setForeground(new java.awt.Color(0, 122, 204));

        Btn_SectionGraphic8.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic8.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic8.setBorder(null);
        Btn_SectionGraphic8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic8ActionPerformed(evt);
            }
        });

        Btn_SectionGraphic9.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic9.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic9.setBorder(null);
        Btn_SectionGraphic9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic9ActionPerformed(evt);
            }
        });

        Btn_SectionGraphic10.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic10.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic10.setBorder(null);
        Btn_SectionGraphic10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic10ActionPerformed(evt);
            }
        });

        Btn_SectionGraphic11.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic11.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic11.setBorder(null);
        Btn_SectionGraphic11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic11ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(45, 45, 48));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Book & Album Covers ");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(45, 45, 48));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Portraits & Caricatures");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(45, 45, 48));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Business Cards & Stationery");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(45, 45, 48));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Web & Mobile Design ");

        jSeparator10.setForeground(new java.awt.Color(0, 122, 204));

        jSeparator11.setForeground(new java.awt.Color(0, 122, 204));

        jSeparator12.setForeground(new java.awt.Color(0, 122, 204));

        jSeparator13.setForeground(new java.awt.Color(0, 122, 204));

        Btn_SectionGraphic12.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic12.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic12.setBorder(null);
        Btn_SectionGraphic12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic12ActionPerformed(evt);
            }
        });

        Btn_SectionGraphic13.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic13.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic13.setBorder(null);
        Btn_SectionGraphic13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic13ActionPerformed(evt);
            }
        });

        Btn_SectionGraphic14.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic14.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic14.setBorder(null);
        Btn_SectionGraphic14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic14ActionPerformed(evt);
            }
        });

        Btn_SectionGraphic15.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic15.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic15.setBorder(null);
        Btn_SectionGraphic15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic15ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(45, 45, 48));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Presentation Design");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(45, 45, 48));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Infographic Design ");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(45, 45, 48));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Cartoons & Comics ");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(45, 45, 48));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Architecture & Floor Plans ");

        jSeparator14.setForeground(new java.awt.Color(0, 122, 204));

        jSeparator15.setForeground(new java.awt.Color(0, 122, 204));

        jSeparator16.setForeground(new java.awt.Color(0, 122, 204));

        jSeparator17.setForeground(new java.awt.Color(0, 122, 204));

        Btn_SectionGraphic16.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic16.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic16.setBorder(null);
        Btn_SectionGraphic16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic16ActionPerformed(evt);
            }
        });

        Btn_SectionGraphic17.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic17.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic17.setBorder(null);
        Btn_SectionGraphic17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic17ActionPerformed(evt);
            }
        });

        Btn_SectionGraphic18.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic18.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic18.setBorder(null);
        Btn_SectionGraphic18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic18ActionPerformed(evt);
            }
        });

        Btn_SectionGraphic19.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic19.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Tree Structure_26px.png"))); // NOI18N
        Btn_SectionGraphic19.setBorder(null);
        Btn_SectionGraphic19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphic19ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(45, 45, 48));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("3D Models & Product Design");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(45, 45, 48));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("T-Shirts & Merchandise ");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(45, 45, 48));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Photoshop Editing ");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(45, 45, 48));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Banner Ads ");

        jSeparator18.setForeground(new java.awt.Color(0, 122, 204));

        jSeparator19.setForeground(new java.awt.Color(0, 122, 204));

        jSeparator20.setForeground(new java.awt.Color(0, 122, 204));

        jSeparator21.setForeground(new java.awt.Color(0, 122, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic19))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Btn_SectionGraphic16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProfileHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProfileHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SectionGraphicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphicActionPerformed

    }//GEN-LAST:event_Btn_SectionGraphicActionPerformed

    private void Btn_SectionGraphic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic1ActionPerformed

    private void Btn_SectionGraphic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic2ActionPerformed

    private void Btn_SectionGraphic4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic4ActionPerformed

    private void Btn_SectionGraphic5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic5ActionPerformed

    private void Btn_SectionGraphic6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic6ActionPerformed

    private void Btn_SectionGraphic7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic7ActionPerformed

    private void Btn_SectionGraphic8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic8ActionPerformed

    private void Btn_SectionGraphic9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic9ActionPerformed

    private void Btn_SectionGraphic10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic10ActionPerformed

    private void Btn_SectionGraphic11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic11ActionPerformed

    private void Btn_SectionGraphic12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic12ActionPerformed

    private void Btn_SectionGraphic13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic13ActionPerformed

    private void Btn_SectionGraphic14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic14ActionPerformed

    private void Btn_SectionGraphic15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic15ActionPerformed

    private void Btn_SectionGraphic16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic16ActionPerformed

    private void Btn_SectionGraphic17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic17ActionPerformed

    private void Btn_SectionGraphic18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic18ActionPerformed

    private void Btn_SectionGraphic19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphic19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionGraphic19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesigningSec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesigningSec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesigningSec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesigningSec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesigningSec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_SectionGraphic;
    private javax.swing.JButton Btn_SectionGraphic1;
    private javax.swing.JButton Btn_SectionGraphic10;
    private javax.swing.JButton Btn_SectionGraphic11;
    private javax.swing.JButton Btn_SectionGraphic12;
    private javax.swing.JButton Btn_SectionGraphic13;
    private javax.swing.JButton Btn_SectionGraphic14;
    private javax.swing.JButton Btn_SectionGraphic15;
    private javax.swing.JButton Btn_SectionGraphic16;
    private javax.swing.JButton Btn_SectionGraphic17;
    private javax.swing.JButton Btn_SectionGraphic18;
    private javax.swing.JButton Btn_SectionGraphic19;
    private javax.swing.JButton Btn_SectionGraphic2;
    private javax.swing.JButton Btn_SectionGraphic4;
    private javax.swing.JButton Btn_SectionGraphic5;
    private javax.swing.JButton Btn_SectionGraphic6;
    private javax.swing.JButton Btn_SectionGraphic7;
    private javax.swing.JButton Btn_SectionGraphic8;
    private javax.swing.JButton Btn_SectionGraphic9;
    private javax.swing.JLabel ProfileHeading;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
