/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package freelauncing.marketplace;
import javax.swing.*;
/**
 *
 * @author Abbas Zaheer
 */
public class MainHome extends javax.swing.JFrame {

    /**
     * Creates new form MainHome
     */
    
    public MainHome() {
        initComponents();
        
       Lbl_Username.setText(SignIn.USERNAME);
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        panel_TopHeaderPanel = new javax.swing.JPanel();
        Lbl_Username = new javax.swing.JLabel();
        Btn_Profile = new javax.swing.JButton();
        Btn_Logout = new javax.swing.JButton();
        Btn_AccountSetting = new javax.swing.JButton();
        Btn_SavedGigs = new javax.swing.JButton();
        Btn_CreateGigs = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        panel_MidPanel = new javax.swing.JPanel();
        textfield_SearchArea = new javax.swing.JTextField();
        Lbl_HeadingTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Btn_SearchButton = new javax.swing.JButton();
        panel_MainPanel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        Btn_SectionGraphic = new javax.swing.JButton();
        Btn_SectionMarketing = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Btn_SectionWritng = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Btn_SectionVideo = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        Btn_SectionMusic = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        Btn_SectionProgrammingTech = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        Btn_SectionBusiness = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        Btn_SectionFunLifeStyle = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Contacts_26px.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_TopHeaderPanel.setBackground(new java.awt.Color(45, 45, 48));

        Lbl_Username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Lbl_Username.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Btn_Profile.setBackground(new java.awt.Color(45, 45, 48));
        Btn_Profile.setForeground(new java.awt.Color(85, 166, 221));
        Btn_Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Registration_26px.png"))); // NOI18N
        Btn_Profile.setBorder(null);
        Btn_Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ProfileActionPerformed(evt);
            }
        });

        Btn_Logout.setBackground(new java.awt.Color(45, 45, 48));
        Btn_Logout.setForeground(new java.awt.Color(85, 166, 221));
        Btn_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Shutdown_26px.png"))); // NOI18N
        Btn_Logout.setBorder(null);
        Btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LogoutActionPerformed(evt);
            }
        });

        Btn_AccountSetting.setBackground(new java.awt.Color(45, 45, 48));
        Btn_AccountSetting.setForeground(new java.awt.Color(85, 166, 221));
        Btn_AccountSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Settings_26px.png"))); // NOI18N
        Btn_AccountSetting.setBorder(null);
        Btn_AccountSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AccountSettingActionPerformed(evt);
            }
        });

        Btn_SavedGigs.setBackground(new java.awt.Color(45, 45, 48));
        Btn_SavedGigs.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SavedGigs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Pin_26px.png"))); // NOI18N
        Btn_SavedGigs.setBorder(null);
        Btn_SavedGigs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SavedGigsActionPerformed(evt);
            }
        });

        Btn_CreateGigs.setBackground(new java.awt.Color(45, 45, 48));
        Btn_CreateGigs.setForeground(new java.awt.Color(85, 166, 221));
        Btn_CreateGigs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Add File_26px.png"))); // NOI18N
        Btn_CreateGigs.setBorder(null);
        Btn_CreateGigs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CreateGigsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_TopHeaderPanelLayout = new javax.swing.GroupLayout(panel_TopHeaderPanel);
        panel_TopHeaderPanel.setLayout(panel_TopHeaderPanelLayout);
        panel_TopHeaderPanelLayout.setHorizontalGroup(
            panel_TopHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_TopHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_AccountSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_SavedGigs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_CreateGigs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_TopHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lbl_Username, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jSeparator10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_TopHeaderPanelLayout.setVerticalGroup(
            panel_TopHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TopHeaderPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panel_TopHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_CreateGigs, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(Btn_SavedGigs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_AccountSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(panel_TopHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_MidPanel.setBackground(new java.awt.Color(45, 45, 48));

        textfield_SearchArea.setBackground(new java.awt.Color(45, 45, 48));
        textfield_SearchArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textfield_SearchArea.setForeground(new java.awt.Color(255, 255, 255));
        textfield_SearchArea.setBorder(null);

        Lbl_HeadingTitle.setFont(new java.awt.Font("Kozuka Mincho Pr6N B", 0, 24)); // NOI18N
        Lbl_HeadingTitle.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_HeadingTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_HeadingTitle.setText("Freelaunce Service Marketplace");

        Btn_SearchButton.setBackground(new java.awt.Color(45, 45, 48));
        Btn_SearchButton.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Search_26px.png"))); // NOI18N
        Btn_SearchButton.setBorder(null);
        Btn_SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_MidPanelLayout = new javax.swing.GroupLayout(panel_MidPanel);
        panel_MidPanel.setLayout(panel_MidPanelLayout);
        panel_MidPanelLayout.setHorizontalGroup(
            panel_MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_MidPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_MidPanelLayout.createSequentialGroup()
                        .addComponent(Lbl_HeadingTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_MidPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel_MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel_MidPanelLayout.createSequentialGroup()
                                .addComponent(textfield_SearchArea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(329, 329, 329))))
        );
        panel_MidPanelLayout.setVerticalGroup(
            panel_MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_MidPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Lbl_HeadingTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textfield_SearchArea, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        panel_MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(0, 122, 204));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(45, 45, 48));
        jLabel11.setText("Graphics & Design");

        Btn_SectionGraphic.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionGraphic.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionGraphic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Paint_26px.png"))); // NOI18N
        Btn_SectionGraphic.setBorder(null);
        Btn_SectionGraphic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionGraphicActionPerformed(evt);
            }
        });

        Btn_SectionMarketing.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionMarketing.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionMarketing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Commercial_26px.png"))); // NOI18N
        Btn_SectionMarketing.setBorder(null);
        Btn_SectionMarketing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionMarketingActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(45, 45, 48));
        jLabel12.setText("Digital Marketing");

        jSeparator3.setForeground(new java.awt.Color(0, 122, 204));

        Btn_SectionWritng.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionWritng.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionWritng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Ball Point Pen_26px.png"))); // NOI18N
        Btn_SectionWritng.setBorder(null);
        Btn_SectionWritng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionWritngActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(45, 45, 48));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Writing & Translation");

        jSeparator4.setForeground(new java.awt.Color(0, 122, 204));

        Btn_SectionVideo.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionVideo.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionVideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Documentary_26px.png"))); // NOI18N
        Btn_SectionVideo.setBorder(null);
        Btn_SectionVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionVideoActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 122, 204));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(45, 45, 48));
        jLabel14.setText("Video & Animation");

        Btn_SectionMusic.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionMusic.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionMusic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Microphone_26px.png"))); // NOI18N
        Btn_SectionMusic.setBorder(null);
        Btn_SectionMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionMusicActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(45, 45, 48));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Music & Audio");

        jSeparator6.setForeground(new java.awt.Color(0, 122, 204));

        Btn_SectionProgrammingTech.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionProgrammingTech.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionProgrammingTech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Google Code_26px.png"))); // NOI18N
        Btn_SectionProgrammingTech.setBorder(null);
        Btn_SectionProgrammingTech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionProgrammingTechActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(45, 45, 48));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Programming & Tech");

        jSeparator7.setForeground(new java.awt.Color(0, 122, 204));

        Btn_SectionBusiness.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionBusiness.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionBusiness.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Handshake_26px.png"))); // NOI18N
        Btn_SectionBusiness.setBorder(null);
        Btn_SectionBusiness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionBusinessActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(45, 45, 48));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Business");

        jSeparator8.setForeground(new java.awt.Color(0, 122, 204));

        Btn_SectionFunLifeStyle.setBackground(new java.awt.Color(255, 255, 255));
        Btn_SectionFunLifeStyle.setForeground(new java.awt.Color(85, 166, 221));
        Btn_SectionFunLifeStyle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Comedy 2_26px.png"))); // NOI18N
        Btn_SectionFunLifeStyle.setBorder(null);
        Btn_SectionFunLifeStyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SectionFunLifeStyleActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(45, 45, 48));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Fun & Lifestyle");

        jSeparator9.setForeground(new java.awt.Color(0, 122, 204));

        javax.swing.GroupLayout panel_MainPanelLayout = new javax.swing.GroupLayout(panel_MainPanel);
        panel_MainPanel.setLayout(panel_MainPanelLayout);
        panel_MainPanelLayout.setHorizontalGroup(
            panel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                .addGroup(panel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panel_MainPanelLayout.createSequentialGroup()
                            .addGroup(panel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(Btn_SectionMusic)))
                            .addGap(34, 34, 34))
                        .addGroup(panel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel11))
                            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(Btn_SectionGraphic))))
                    .addGroup(panel_MainPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(Btn_SectionMarketing)))
                        .addGap(74, 74, 74))
                    .addGroup(panel_MainPanelLayout.createSequentialGroup()
                        .addGroup(panel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(Btn_SectionProgrammingTech))
                            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)))
                .addGroup(panel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_MainPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(Btn_SectionWritng))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_MainPanelLayout.createSequentialGroup()
                        .addGroup(panel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(Btn_SectionBusiness))
                            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)))
                .addGroup(panel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_MainPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(panel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(Btn_SectionFunLifeStyle))
                            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(Btn_SectionVideo))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_MainPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_MainPanelLayout.setVerticalGroup(
            panel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_MainPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(panel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_MainPanelLayout.createSequentialGroup()
                        .addComponent(Btn_SectionVideo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(panel_MainPanelLayout.createSequentialGroup()
                        .addComponent(Btn_SectionWritng)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(panel_MainPanelLayout.createSequentialGroup()
                        .addComponent(Btn_SectionMarketing)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(panel_MainPanelLayout.createSequentialGroup()
                        .addComponent(Btn_SectionGraphic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(panel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_MainPanelLayout.createSequentialGroup()
                        .addComponent(Btn_SectionMusic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_MainPanelLayout.createSequentialGroup()
                        .addComponent(Btn_SectionProgrammingTech)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_MainPanelLayout.createSequentialGroup()
                        .addComponent(Btn_SectionBusiness)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_MainPanelLayout.createSequentialGroup()
                        .addComponent(Btn_SectionFunLifeStyle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)))
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_TopHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_MidPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_TopHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_MidPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SectionGraphicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionGraphicActionPerformed
       
    }//GEN-LAST:event_Btn_SectionGraphicActionPerformed

    private void Btn_SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SearchButtonActionPerformed

    private void Btn_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ProfileActionPerformed
        UserProfile userProfile = new UserProfile();
                                    
                                    userProfile.setVisible(true);
                                    userProfile.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                    userProfile.setResizable(false);
                                    userProfile.setLocation(250, 20);
                                    userProfile.setTitle("Freelaunce Service Marketplace");
    }//GEN-LAST:event_Btn_ProfileActionPerformed

    private void Btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LogoutActionPerformed
        this.dispose();
    }//GEN-LAST:event_Btn_LogoutActionPerformed

    private void Btn_AccountSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AccountSettingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_AccountSettingActionPerformed

    private void Btn_SavedGigsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SavedGigsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SavedGigsActionPerformed

    private void Btn_CreateGigsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CreateGigsActionPerformed
       CreateAGig creatingGig = new CreateAGig();
                                    
                                    creatingGig.setVisible(true);
                                    creatingGig.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                    creatingGig.setResizable(false);
                                    creatingGig.setLocation(250, 20);
                                    creatingGig.setTitle("Freelaunce Service Marketplace");
    }//GEN-LAST:event_Btn_CreateGigsActionPerformed

    private void Btn_SectionMarketingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionMarketingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionMarketingActionPerformed

    private void Btn_SectionWritngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionWritngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionWritngActionPerformed

    private void Btn_SectionVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionVideoActionPerformed

    private void Btn_SectionMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionMusicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionMusicActionPerformed

    private void Btn_SectionProgrammingTechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionProgrammingTechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionProgrammingTechActionPerformed

    private void Btn_SectionBusinessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionBusinessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionBusinessActionPerformed

    private void Btn_SectionFunLifeStyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SectionFunLifeStyleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SectionFunLifeStyleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_AccountSetting;
    private javax.swing.JButton Btn_CreateGigs;
    private javax.swing.JButton Btn_Logout;
    private javax.swing.JButton Btn_Profile;
    private javax.swing.JButton Btn_SavedGigs;
    private javax.swing.JButton Btn_SearchButton;
    private javax.swing.JButton Btn_SectionBusiness;
    private javax.swing.JButton Btn_SectionFunLifeStyle;
    private javax.swing.JButton Btn_SectionGraphic;
    private javax.swing.JButton Btn_SectionMarketing;
    private javax.swing.JButton Btn_SectionMusic;
    private javax.swing.JButton Btn_SectionProgrammingTech;
    private javax.swing.JButton Btn_SectionVideo;
    private javax.swing.JButton Btn_SectionWritng;
    private javax.swing.JLabel Lbl_HeadingTitle;
    private javax.swing.JLabel Lbl_Username;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel panel_MainPanel;
    private javax.swing.JPanel panel_MidPanel;
    private javax.swing.JPanel panel_TopHeaderPanel;
    private javax.swing.JTextField textfield_SearchArea;
    // End of variables declaration//GEN-END:variables
}
