/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package freelauncing.marketplace;

import javax.swing.*;
import java.awt.*;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.lang.*;
import java.util.Scanner;

/**
 *
 * @author Abbas Zaheer
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
        
    Container c = this.getContentPane();
    
    protected static String USERNAME;
    protected static String PASSOWORD;
    
    
    public SignIn() {
        initComponents();
       
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        RightPanel = new javax.swing.JPanel();
        label_Username = new javax.swing.JLabel();
        textfield_Username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        label_Password = new javax.swing.JLabel();
        passwordfield_Password = new javax.swing.JPasswordField();
        label_Question = new javax.swing.JLabel();
        label_ImageIcon = new javax.swing.JLabel();
        Btn_SignIn = new javax.swing.JButton();
        Btn_CreateAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/new.png"))); // NOI18N

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        RightPanel.setBackground(new java.awt.Color(45, 45, 48));

        label_Username.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_Username.setForeground(new java.awt.Color(85, 166, 221));
        label_Username.setText("Username");

        textfield_Username.setBackground(new java.awt.Color(45, 45, 48));
        textfield_Username.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textfield_Username.setForeground(new java.awt.Color(255, 255, 255));
        textfield_Username.setBorder(null);
        textfield_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_UsernameActionPerformed(evt);
            }
        });

        label_Password.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_Password.setForeground(new java.awt.Color(85, 166, 221));
        label_Password.setText("Password");

        passwordfield_Password.setBackground(new java.awt.Color(45, 45, 48));
        passwordfield_Password.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        passwordfield_Password.setForeground(new java.awt.Color(255, 255, 255));
        passwordfield_Password.setBorder(null);
        passwordfield_Password.setCaretColor(new java.awt.Color(255, 255, 255));
        passwordfield_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfield_PasswordActionPerformed(evt);
            }
        });

        label_Question.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_Question.setForeground(new java.awt.Color(85, 166, 221));
        label_Question.setText("Not registered?");

        label_ImageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelauncing/marketplace/Male User_104px.png"))); // NOI18N

        Btn_SignIn.setBackground(new java.awt.Color(225, 225, 225));
        Btn_SignIn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Btn_SignIn.setText("Sign in");
        Btn_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SignInActionPerformed(evt);
            }
        });

        Btn_CreateAccount.setBackground(new java.awt.Color(45, 45, 48));
        Btn_CreateAccount.setForeground(new java.awt.Color(85, 166, 221));
        Btn_CreateAccount.setText("Create an account");
        Btn_CreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CreateAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightPanelLayout = new javax.swing.GroupLayout(RightPanel);
        RightPanel.setLayout(RightPanelLayout);
        RightPanelLayout.setHorizontalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_SignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(RightPanelLayout.createSequentialGroup()
                        .addComponent(label_Question)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(Btn_CreateAccount))
                    .addComponent(jSeparator2)
                    .addComponent(label_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_Username)
                    .addComponent(label_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1)
                    .addComponent(passwordfield_Password))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_ImageIcon)
                .addGap(121, 121, 121))
        );
        RightPanelLayout.setVerticalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label_ImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordfield_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(Btn_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_CreateAccount)
                    .addComponent(label_Question))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(RightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfield_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_UsernameActionPerformed

    private void passwordfield_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfield_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfield_PasswordActionPerformed

    private void Btn_CreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CreateAccountActionPerformed
        SignUp signUp = new SignUp(); 
        signUp.setVisible(true);
        signUp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        signUp.setResizable(false);
        signUp.setLocation(250, 100);
        signUp.setTitle("Freelaunce Service Marketplace");
    }//GEN-LAST:event_Btn_CreateAccountActionPerformed

    private void Btn_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SignInActionPerformed
        String username, password;
        
        username=textfield_Username.getText();
        password=new String (passwordfield_Password.getPassword());
        
        if(username.isEmpty() || password.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please enter username or password !");
        }
        else
        {
            Scanner fin =null;
            try {
                fin = new Scanner(new FileInputStream("RegisteredUsers.txt"));
                boolean checking=false;
                String line,line2;
                                while(fin.hasNextLine())//searching and checking the username.
                                {
                                    line=fin.nextLine();
                                    if(line.equals(username))
                                    {
                                        line2=fin.nextLine();
                                        if(line2.equals(password))
                                        {
                                            checking=true;    
                                            break;
                                        }
                                        
                                    }
                                }
                fin.close();
                                if(checking==true)
                                {
                                    USERNAME=username;
                                    PASSOWORD=password;
                                    
                                    textfield_Username.setText("");
                                    passwordfield_Password.setText("");
                                    
                                    MainHome mainHome = new MainHome();
                                    
                                    mainHome.setVisible(true);
                                    mainHome.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                    mainHome.setResizable(false);
                                    mainHome.setLocation(250, 20);
                                    mainHome.setTitle("Freelaunce Service Marketplace");
                                    
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(this, "Username or Password is invalid !");
                                }
                
                //=================================================================================================================
                
                //=================================================================================================================
                
                
            } 
            catch (FileNotFoundException e) {
                System.out.println("File Not Found");
                System.exit(0);
            }
        }
    }//GEN-LAST:event_Btn_SignInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_CreateAccount;
    private javax.swing.JButton Btn_SignIn;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_ImageIcon;
    private javax.swing.JLabel label_Password;
    private javax.swing.JLabel label_Question;
    private javax.swing.JLabel label_Username;
    private javax.swing.JPasswordField passwordfield_Password;
    private javax.swing.JTextField textfield_Username;
    // End of variables declaration//GEN-END:variables
}
