/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package freelauncing.marketplace;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.io.Writer;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Abbas Zaheer
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    ButtonGroup g = new ButtonGroup();
    
    public SignUp() {
        initComponents();
        
        g.add(radiobtn_Male);
        g.add(radiobtn_Female);
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        label_FirstName = new javax.swing.JLabel();
        textfield_FirstName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        label_LastName = new javax.swing.JLabel();
        textfield_LastName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        label_Email = new javax.swing.JLabel();
        textfield_Email = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        label_Gender = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        label_Country = new javax.swing.JLabel();
        textfield_Country = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        textfield_Username = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        label_Password = new javax.swing.JLabel();
        textfield_Password = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        label_ConfirmPassword = new javax.swing.JLabel();
        textfield_ConfirmPassword = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        radiobtn_Male = new javax.swing.JRadioButton();
        radiobtn_Female = new javax.swing.JRadioButton();
        title_CreateAccount = new javax.swing.JLabel();
        Btn_SignUp = new javax.swing.JButton();
        label_Username = new javax.swing.JLabel();
        Btn_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 45, 48));

        label_FirstName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_FirstName.setForeground(new java.awt.Color(85, 166, 221));
        label_FirstName.setText("First Name *");

        textfield_FirstName.setBackground(new java.awt.Color(45, 45, 48));
        textfield_FirstName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textfield_FirstName.setForeground(new java.awt.Color(255, 255, 255));
        textfield_FirstName.setBorder(null);
        textfield_FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_FirstNameActionPerformed(evt);
            }
        });

        label_LastName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_LastName.setForeground(new java.awt.Color(85, 166, 221));
        label_LastName.setText("Last Name *");

        textfield_LastName.setBackground(new java.awt.Color(45, 45, 48));
        textfield_LastName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textfield_LastName.setForeground(new java.awt.Color(255, 255, 255));
        textfield_LastName.setBorder(null);
        textfield_LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_LastNameActionPerformed(evt);
            }
        });

        label_Email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_Email.setForeground(new java.awt.Color(85, 166, 221));
        label_Email.setText("Email *");

        textfield_Email.setBackground(new java.awt.Color(45, 45, 48));
        textfield_Email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textfield_Email.setForeground(new java.awt.Color(255, 255, 255));
        textfield_Email.setBorder(null);
        textfield_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_EmailActionPerformed(evt);
            }
        });

        label_Gender.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_Gender.setForeground(new java.awt.Color(85, 166, 221));
        label_Gender.setText("Gender *");

        label_Country.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_Country.setForeground(new java.awt.Color(85, 166, 221));
        label_Country.setText("Country *");

        textfield_Country.setBackground(new java.awt.Color(45, 45, 48));
        textfield_Country.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textfield_Country.setForeground(new java.awt.Color(255, 255, 255));
        textfield_Country.setBorder(null);
        textfield_Country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_CountryActionPerformed(evt);
            }
        });

        textfield_Username.setBackground(new java.awt.Color(45, 45, 48));
        textfield_Username.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textfield_Username.setForeground(new java.awt.Color(255, 255, 255));
        textfield_Username.setBorder(null);
        textfield_Username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textfield_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_UsernameActionPerformed(evt);
            }
        });

        label_Password.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_Password.setForeground(new java.awt.Color(85, 166, 221));
        label_Password.setText("Password *");

        textfield_Password.setBackground(new java.awt.Color(45, 45, 48));
        textfield_Password.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textfield_Password.setForeground(new java.awt.Color(255, 255, 255));
        textfield_Password.setBorder(null);
        textfield_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_PasswordActionPerformed(evt);
            }
        });

        label_ConfirmPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_ConfirmPassword.setForeground(new java.awt.Color(85, 166, 221));
        label_ConfirmPassword.setText("Confirm Password *");

        textfield_ConfirmPassword.setBackground(new java.awt.Color(45, 45, 48));
        textfield_ConfirmPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textfield_ConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        textfield_ConfirmPassword.setBorder(null);
        textfield_ConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_ConfirmPasswordActionPerformed(evt);
            }
        });

        radiobtn_Male.setBackground(new java.awt.Color(45, 45, 48));
        radiobtn_Male.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        radiobtn_Male.setForeground(new java.awt.Color(255, 255, 255));
        radiobtn_Male.setText("Male");

        radiobtn_Female.setBackground(new java.awt.Color(45, 45, 48));
        radiobtn_Female.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        radiobtn_Female.setForeground(new java.awt.Color(255, 255, 255));
        radiobtn_Female.setText("Female");

        title_CreateAccount.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        title_CreateAccount.setForeground(new java.awt.Color(129, 129, 131));
        title_CreateAccount.setText("Create an account");

        Btn_SignUp.setBackground(new java.awt.Color(85, 166, 221));
        Btn_SignUp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Btn_SignUp.setForeground(new java.awt.Color(255, 255, 255));
        Btn_SignUp.setText("Sign Up");
        Btn_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SignUpActionPerformed(evt);
            }
        });

        label_Username.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_Username.setForeground(new java.awt.Color(85, 166, 221));
        label_Username.setText("Username *");

        Btn_Cancel.setBackground(new java.awt.Color(129, 129, 131));
        Btn_Cancel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Btn_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Cancel.setText("Cancel");
        Btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(title_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator3)
                                    .addComponent(label_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textfield_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator8)
                                    .addComponent(textfield_ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator1)
                                        .addComponent(textfield_FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                        .addComponent(label_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator2)
                                        .addComponent(textfield_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label_LastName)))
                                .addGap(116, 116, 116)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_Country, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textfield_Country, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(radiobtn_Male)))
                                        .addGap(18, 18, 18)
                                        .addComponent(radiobtn_Female, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator7)
                                        .addComponent(textfield_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator6)
                                        .addComponent(textfield_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label_Username)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Btn_Cancel)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_SignUp)))
                        .addGap(58, 58, 58))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radiobtn_Male)
                            .addComponent(radiobtn_Female))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_Username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_Country, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_Country, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_SignUp)
                    .addComponent(Btn_Cancel))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfield_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_FirstNameActionPerformed

    private void textfield_LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_LastNameActionPerformed

    private void textfield_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_EmailActionPerformed

    private void textfield_CountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_CountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_CountryActionPerformed

    private void textfield_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_UsernameActionPerformed

    private void textfield_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_PasswordActionPerformed

    private void textfield_ConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_ConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_ConfirmPasswordActionPerformed

    private void Btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_Btn_CancelActionPerformed

    private void Btn_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SignUpActionPerformed
        
        String firstName, lastName, email, country, username, password;
        boolean male=false,female=false;
        
        firstName=textfield_FirstName.getText();
        lastName=textfield_LastName.getText();
        email=textfield_Email.getText();
        
        if(radiobtn_Male.isSelected())
            male=true;
        else
            female=true;
        
        country=textfield_Country.getText();
        username=textfield_Username.getText();
        password=textfield_Password.getText();
        
        //Validations 1
        if(firstName.isEmpty() || lastName.isEmpty() || email.isEmpty() || (male==false && female==false) || country.isEmpty() ||
                username.isEmpty() || textfield_Password.equals("") || textfield_ConfirmPassword.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please fill the compulsory fields !");
        }
        else
        {
            //Validations 2
            if(email.contains("@"))
            {
                //Validations 3
                if(textfield_Password.getText().equals(textfield_ConfirmPassword.getText()))
                {
                    //Validations 4
                    if(password.length()>=8 && username.length()>=8)
                    {
                        //===============================================================================================================================
                            boolean checking=false;
                            Scanner fin = null;
                            try
                            {
                                File file = new File("RegisteredUsers.txt");
                                if(file.createNewFile())
                                {
                                    //System.out.println("file created");
                                }
                                
                                fin = new Scanner(new FileInputStream("RegisteredUsers.txt"));
                                
                                String line;
                                while(fin.hasNextLine())//searching and checking the username.
                                {
                                    line=fin.nextLine();
                                    if(line.equals(username))
                                    {
                                        checking=true;
                                        break;
                                    }
                                }
                                
                                fin.close();
                                //Validations 5
                                if(checking==false)
                                {
                                    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                    
                                    PrintWriter fout = null;
                                    
                                    try {
                                        fout = new PrintWriter(new FileOutputStream("RegisteredUsers.txt",true));
                                        
                                        fout.println(username);
                                        fout.println(password);
                                        fout.println(email);
                                        fout.println(firstName);
                                        fout.println(lastName);
                                        
                                        if(male==true)
                                            fout.println("Male");
                                        else
                                            fout.println("Female");
                                        
                                        fout.println(country);
                                        fout.println("</TheEndOfEachRecord>");
                                        fout.close();
                                        JOptionPane.showMessageDialog(this, "Account created successfully !");
                                        this.dispose();
                                    } 
                                    catch (Exception e)
                                    {
                                        System.out.println("File Not Found");
                                        System.exit(0);
                                        
                                    }
                                        
                                    
                                    
                                    
                                    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(this, "Username already in use, try another one !");
                                }//Validations 5 - end
                                
                            }
                            catch(FileNotFoundException e)
                            {
                                System.out.println("File Not Found");
                                System.exit(0);
                            } catch (IOException ex) {
                            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
                            
                        //===============================================================================================================================
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Username & Password length should be greater than 7 characters !");
                    }//Validations 4 - end
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Password is not matching !");
                }//Validations 3 - end
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Invalid email !");
            }//Validations 2 - end
        }//Validations 1 - end
        
        
    }//GEN-LAST:event_Btn_SignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cancel;
    private javax.swing.JButton Btn_SignUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel label_ConfirmPassword;
    private javax.swing.JLabel label_Country;
    private javax.swing.JLabel label_Email;
    private javax.swing.JLabel label_FirstName;
    private javax.swing.JLabel label_Gender;
    private javax.swing.JLabel label_LastName;
    private javax.swing.JLabel label_Password;
    private javax.swing.JLabel label_Username;
    private javax.swing.JRadioButton radiobtn_Female;
    private javax.swing.JRadioButton radiobtn_Male;
    private javax.swing.JTextField textfield_ConfirmPassword;
    private javax.swing.JTextField textfield_Country;
    private javax.swing.JTextField textfield_Email;
    private javax.swing.JTextField textfield_FirstName;
    private javax.swing.JTextField textfield_LastName;
    private javax.swing.JTextField textfield_Password;
    private javax.swing.JTextField textfield_Username;
    private javax.swing.JLabel title_CreateAccount;
    // End of variables declaration//GEN-END:variables

    private Writer FileOutputStream(String registeredUsers, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
